### ISSUE TITLE
`exceptions` vs `tracedExceptions`

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#922] opened 2024-08-12 10:50 UTC
The HUB module contains an object
```java
short exceptions;
```
- How is it generated ?
- Does it contain `all errors` that are currently active or is it filtered ?
  - if it is the full account of all issues (which is what I hope) then we need a filtered version, the one that will be traced in the HUB

```java
public short tracedExceptions() { ... }
```

**Comment by letypequividelespoubelles** [comment] 2024-09-06 07:56
duplicate of #1118

**Closed as completed by letypequividelespoubelles** 2024-09-06 07:56 UTC
Labels: bug
