### ISSUE TITLE
Re-implement GAS

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#916] opened 2024-08-11 01:19 UTC
Re-implement the GAS module as specified in https://github.com/Consensys/linea-specification-internal/pull/538

**Comment by lorenzogentile404** [comment] 2024-08-22 20:24
WIP in https://github.com/Consensys/linea-tracer/tree/feat/issue-746/linea-transaction-class.

**Comment by letypequividelespoubelles** [comment] 2024-09-02 05:56
duplicate of #1026

**Closed as completed by letypequividelespoubelles** 2024-09-02 05:56 UTC
Labels: enhancement
