### ISSUE TITLE
fix(blockhash): `blockhash-into-wcp-lower-bound` lookup and `constency` constraint failing in reference tests

### ISSUE THREAD

**Issue by lorenzogentile404** [Consensys/besu-sequencer-plugins#1297] opened 2024-09-24 10:43 UTC

**Comment by lorenzogentile404** [comment] 2024-09-24 10:45
[failedBlockchainReferenceTests 11.json](https://github.com/user-attachments/files/17113262/failedBlockchainReferenceTests.11.json)

**Comment by letypequividelespoubelles** [comment] 2024-09-25 07:46
is it linked to https://github.com/Consensys/linea-specification-internal/issues/611

**Comment by letypequividelespoubelles** [comment] 2024-09-25 07:49
sorry, I meant https://github.com/Consensys/linea-specification-internal/issues/610

**Comment by letypequividelespoubelles** [comment] 2024-11-28 09:19
duplicate of #1527

**Closed as completed by letypequividelespoubelles** 2024-11-28 09:19 UTC
Labels: reference test
