### ISSUE TITLE
`ROM` tests

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1412] opened 2024-10-15 00:45 UTC
## Parametric tests

A single test per pair `0 ≤ j ≤ k` and `1 ≤ k ≤ 32`.
```rust
// simplified instructions to chain:
PUSHk 0x ff ff ... ff // with j ≤ k differents ff's
```

## One single large test

```rust
// simplified instructions to chain:
PUSHk 0x 5b 5b ... 5b // with j repetitions of 5b ≡ JUMPDEST, where 0 ≤ j ≤ k and 1 ≤ k ≤ 32
```

The code should be a concatenation of all of the ~ 512 such pairs concatenated in some fixed, random order. The best solution would be to provide the code a string of bytes.

**Note.** the value `5b` allows a program to move forward to the next `PUSH`.

**Comment by letypequividelespoubelles** [comment] 2024-10-15 07:52
duplicate of #309

**Comment by lorenzogentile404** [comment] 2024-10-16 09:35
Received. I imagine:

```
\forall l, k \in {0,...32} such that l <= k

\forall a, b, c, k \in {0,32} such that a + b + c == k
```

**Closed as completed** 2024-10-21 13:30 UTC
Labels: testing
