### ISSUE TITLE
Duplicate of #1061

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1109] opened 2024-09-05 16:29 UTC
Duplicate of #1061

## Ranges

```rust
6690-6699
```

## Issue

See #1061

**Comment by letypequividelespoubelles** [comment] 2024-09-06 04:21
what's the point of creating a duplicate of the issue ?

**Comment by letypequividelespoubelles** [comment] 2024-09-06 05:36
test is passing wo any modif : 
![image](https://github.com/user-attachments/assets/6a28e03c-c169-4dc5-8bc2-85cacf39ca86)

**Closed as completed by letypequividelespoubelles** 2024-09-06 05:36 UTC
Labels: bug, ranges
