### ISSUE TITLE
Capturing blockhashes

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1009] opened 2024-08-28 09:55 UTC
Blockhashes aren't being captured by replays. There are thus 2 issues here:

1. their capture and inclusion in the replay test json file
2. getting the replay tests to feed these blockhashes to the EVM testing environment

This issue is connected to https://github.com/Consensys/linea-tracer/issues/996.

**Comment by letypequividelespoubelles** [comment] 2024-08-28 11:17
duplicate of #935

**Closed as completed by letypequividelespoubelles** 2024-08-28 11:17 UTC
