### ISSUE TITLE
`FullExceptions` vs `TracedException`

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1118] opened 2024-09-06 07:29 UTC
We need two `Exceptions` objects:
- the "full" exceptions object that records all exceptions happening for a given instruction
- the "traced" exceptions object that records the exception which we wish to act upon

The `TracedException` will be used in the tracing of the stack-rows. We must have the property that
- `TracedException` is always pure (i.e. a single power of 2 or zero i.e. it's a `short` with at most one nonzero binary digit)
- `TracedException = 0 <=> FullExceptions = 0`
- If `TracedException = (1 << k)` then the `k`-th bit of `FullExceptions` is `1`

Also the `Gas.java` should be using the `TracedException` to determine the `outOfGasException` flag.

-----

Example of what we would like to achieve for the `CallSection`, for instance:

```java
    // STATICX cases
    if (Exceptions.staticFault(exceptions)) {
      this.commonValues.tracedException == Exceptions.STATIC_FAULT;
      return;
    }

    // ...

    // MXPX case
    if (Exceptions.memoryExpansionException(exceptions)) {
      this.commonValues.tracedException == Exceptions.MEMORY_EXPANSION_EXCEPTION;
      return;
    }

    // ...

    // OOGX case
    if (Exceptions.outOfGasException(exceptions)) {
      this.commonValues.tracedException == Exceptions.OUT_OF_GAS_EXCEPTION;
      this.oogXCall(hub);
      return;
    }
```

The end goal is to replace `exceptions` below with `tracedExceptions` in the tracing of `StackFragmet.java`

```java
        // Exception flag // this is WRONG
        .pStackOpcx(Exceptions.invalidCodePrefix(exceptions))
        .pStackSux(Exceptions.stackUnderflow(exceptions))
        .pStackSox(Exceptions.stackOverflow(exceptions))
        .pStackMxpx(Exceptions.memoryExpansionException(exceptions))
        .pStackOogx(Exceptions.outOfGasException(exceptions))
        .pStackRdcx(Exceptions.returnDataCopyFault(exceptions))
        .pStackJumpx(Exceptions.jumpFault(exceptions))
        .pStackStaticx(Exceptions.staticFault(exceptions))
        .pStackSstorex(Exceptions.outOfSStore(exceptions))
        .pStackIcpx(contextExceptions.invalidCodePrefix())
        .pStackMaxcsx(contextExceptions.codeSizeOverflow())
```

**Comment by letypequividelespoubelles** [comment] 2024-09-06 07:55
duplicate of #922

**Comment by lorenzogentile404** [comment] 2024-09-06 08:00
Propose: centralise logic in the Exception object and define hierarchy. More details to come.

**Comment by OlivierBBB** [comment] 2024-09-06 11:36
`TracedException` could alternatively be an `enum`, which would be cleaner.

**Closed as completed** 2024-09-12 11:16 UTC
Labels: enhancement
